language: ruby
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install: gem install bundler -v 1.15.1
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE test_by_spec;'
